### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by benio1394** [ViciousBadger/larion-disc-world#2]
Hello, I want to ask you about a few things, but unfortunably, modrinth don't have comment section. Sorry for the problem.

1. What value should I replace in data/laron/worldgen/density_function/overworld/circle.json to have a world with 4500 block radius?

2. Do you have plans for removing rare, but pretty tall terrain spikes? They looks a little bit strange.

3. Do you know if larion works well on server? Is the new height limit could be a performance issue?

4. Do you have discord server for your community?

**Comment by ViciousBadger** [comment]
Hi, these are some good questions.

1. In the readme I've given the a formula to use, but maybe I didnt explain it well. In your case `4500^-1 = 0.000222{...}`, so you would write 0.00022222222 in the fields that are currently 0.0002.
2. They are intentional, it's what is called "windswept" terrain in biomes such as windswept forest, savanna etc. They are weird but I like them, though I wish I could make them a little less tall... apparently they get taller with more world height.. If you want to remove them completely you can edit the core Larion datapack, in the file `data/larion/worldgen/density_function/overworld/erosion.json`, remove the entire "windswept" section from the calculation, like this:

```
{
  "type": "minecraft:min",
  "argument1": {
    "type": "minecraft:mul",
    "argument1": "larion:overworld/erosion/mountain_chains",
    "argument2": -1.0
  },
  "argument2": {
    "type": "minecraft:range_choice",
    "input": "larion:overworld/erosion/swamps",
    "min_inclusive": 0.40,
    "max_exclusive": 0.60,
    "when_in_range": 0.40,
    "when_out_of_range": "larion:overworld/erosion/swamps"
  }
}
```
3. I don't know about performance, it's a complex topic, but it is certainly a little slower to generate terrain on my machine.. I'm torn on this because the extra world height is really good for mountains and I plan on eventually making caves go deeper as well.. you also have to run a Fabric server which is less performant than things like Papermc, but at least there are a lot of optimization mods that can counter-balance the loss.
4. I don't plan on starting a Discord server, I hear it comes with moderation and drama etc.. maybe at some point Larion would be its own channel on an existing server with a good community.

**Comment by benio1394** [comment]
Thank you for quick answer and explaining everything. I want to say that you've made amazing job with this two mods, I always dreamed about something like this in minecraft. I hope this project will gain the recognition that it deserves. And for the discord - you are right, maybe github communication will be less problematic. Good luck with your work and thank you one more time.

**Comment by ViciousBadger** [comment]
Hey thanks a lot. I'm sure it will get noticed in time if people enjoy it as much as I do.

For your info I've released yet another new version (3.2) of Larion, among other things I managed to reduce the intensity of the "terrain spikes" you mentioned, they are still there but much less janky :)

**Comment by ViciousBadger** [comment]
1. It does require Larion in practice because of how it's put together, but in theory you could do the same kind of effect for vanilla terrain or any other kind of terrain, like Continents does. I think Klinbee (guy behind More Density Functions) is cooking up something atm, keep an eye on his modrinth page. About biomes, that's a consequence of how Larion makes biomes smaller. Modded biomes often end up making them even smaller due to technical reasons.
2. Yes, I wanted it this way :) I also wanted them to be way more vertical but they're a little tame now. There are rare cases of larger mushroom islands.
3. In v3.2.0 I tried to make it generate a bit more flat terrain, but in general the point is for terrain to be very rugged, except in deserts.
4. Stony peaks are not snowy, and there are some really tall hills with meadows and plains and forests and so on, but in general mountains are snowcapped, that's just how Minecraft is, it's not really a Larion thing :)

**Comment by ViciousBadger** [comment]
For swamps, try messing with `swamps.json` and `swamps_base.json` in the .jar/.zip. This will actually also affect mushroom islands as they use the same noise. For cherry groves, I'm not sure how to improve without affecting other things too much.

**Comment by benio1394** [comment]
Hello again. I've played a little bit with Larion and I wonder if you could add support for Big Biomes world type? This probably require bigger landmass, but in my imagination biomes would be bigger, but not such big like in vanilla big biomes. I ask about this, because what I noticed is that the biomes are frequently rather small and because of that I can't immerse mysefl into the journey in for example jungle, because suddenly I m on the desert or in the forest. Hope it is in line with your plans.

**Comment by ViciousBadger** [comment]
Heyo, actually i was planning to make biomes (vegetation zones) larger for 3.7, I found a way to make them distributed better. I also want to support "large biomes" but also with larger continents and mountain ranges, haven't made it work yet, it's annoying because I have to basically duplicate every single file to large_biomes and change a ton of file references.. ugh

**Comment by benio1394** [comment]
Happy to hear that you already working on it and soory to hear that is so annoying. I try to mess with data by myself and it was a litlle bit scary. Fingers crossed
